// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXB1b6foZhTVmHauGPbnNHkLcF7ELClbM',
    appId: '1:814473854373:android:5d2273c583cdd8061dfc4c',
    messagingSenderId: '814473854373',
    projectId: 'we-chat-797f2',
    storageBucket: 'we-chat-797f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUoBy4P7ajjz50KlsrDEZiFevBul7z4g',
    appId: '1:814473854373:ios:f5d79a077a33440a1dfc4c',
    messagingSenderId: '814473854373',
    projectId: 'we-chat-797f2',
    storageBucket: 'we-chat-797f2.appspot.com',
    androidClientId: '814473854373-hphbqh92sh331pu5t8b2aj87hlirkvf9.apps.googleusercontent.com',
    iosClientId: '814473854373-da29m2a41hkifgdf11s0r125dmp5m778.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
